I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1196, in script
    MC "I’m not much of a looker myself."
Exception: Say has image attributes ('T',), but there's no image tag associated with the speaking character.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1196, in script
    MC "I’m not much of a looker myself."
  File "D:\RENPY\renpy-8.3.4-sdk\renpy\ast.py", line 2586, in execute
    Say.execute(self)
  File "D:\RENPY\renpy-8.3.4-sdk\renpy\ast.py", line 623, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "D:\RENPY\renpy-8.3.4-sdk\renpy\exports\sayexports.py", line 132, in say
    who(what, *args, **kwargs)
  File "D:\RENPY\renpy-8.3.4-sdk\renpy\character.py", line 1407, in __call__
    old_attr_state = self.handle_say_attributes(False, interact)
  File "D:\RENPY\renpy-8.3.4-sdk\renpy\character.py", line 1223, in handle_say_attributes
    if self.resolve_say_attributes(predicting, attrs):
  File "D:\RENPY\renpy-8.3.4-sdk\renpy\character.py", line 1149, in resolve_say_attributes
    raise Exception("Say has image attributes %r, but there's no image tag associated with the speaking character." % (attrs,))
Exception: Say has image attributes ('T',), but there's no image tag associated with the speaking character.

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.7.25031702
